[package]
name = "smush-convert-bot"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

[dependencies.serenity]
default-features = false
version = "0.5"
features = [
    "builder",
    "model",
    "client",
    "framework",
    "standard_framework"
]

[path.serenity]
openssl = "0.10"
